server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka # discovery server location which is localhost for now

spring:
  application:
    name: gateway-service

zuul:
  ignored-services:
  routes:
    oauth2-service:
      path: /oauth/**
      serviceId=auth-service
      stripPrefix:false
    blog-service:
      path: /blog/**
      serviceId=blog-service

ribbon.ConnectTimeout=10000
ribbon.ReadTimeout=10000


